import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: ['class'],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--theme-border))',
        input: 'hsl(var(--color-input-bg))',
        ring: 'hsl(var(--theme-primary) / 0.25)',
        background: 'hsl(var(--theme-background))',
        foreground: 'hsl(var(--theme-foreground))',

        theme: {
          bg: {
            canvas: 'hsl(var(--theme-background))',
            surface: 'hsl(var(--theme-surface))',
            'surface-alt': 'hsl(var(--theme-surface-alt))',
            muted: 'hsl(var(--theme-muted))',
            subtle: 'hsl(var(--theme-subtle))',
            overlay: 'hsl(var(--theme-overlay))',
          },
          text: {
            canvas: 'hsl(var(--theme-foreground))',
            primary: 'hsl(var(--theme-text-primary))',
            secondary: 'hsl(var(--theme-text-secondary))',
            tertiary: 'hsl(var(--theme-text-tertiary))',
            reversed: 'hsl(var(--theme-background))',
          },
          border: {
            DEFAULT: 'hsl(var(--theme-border))',
            muted: 'hsl(var(--theme-border-muted))',
            subtle: 'hsl(var(--theme-border-subtle))',
            strong: 'hsl(var(--theme-border-strong))',
          },
          accent: {
            primary: 'hsl(var(--theme-primary))',
            secondary: 'hsl(var(--theme-primary) / 0.85)',
            tertiary: 'hsl(var(--theme-primary) / 0.7)',
            bg: 'hsl(var(--theme-success-bg))',
            'bg-subtle': 'hsl(var(--theme-surface-alt))',
            fg: 'hsl(var(--theme-primary-foreground))',
          },
          success: {
            primary: 'hsl(var(--theme-success))',
            bg: 'hsl(var(--theme-success-bg))',
            text: 'hsl(var(--theme-success-text))',
          },
          warning: {
            primary: 'hsl(var(--theme-warning))',
            bg: 'hsl(var(--theme-warning-bg))',
            text: 'hsl(var(--theme-warning-text))',
          },
          error: {
            primary: 'hsl(var(--theme-error))',
            bg: 'hsl(var(--theme-error-bg))',
            text: 'hsl(var(--theme-error-text))',
          },
          info: {
            primary: 'hsl(var(--theme-info))',
            bg: 'hsl(var(--theme-info-bg))',
            text: 'hsl(var(--theme-info-text))',
          },

          card: {
            bg: 'hsl(var(--color-card-bg))',
            DEFAULT: 'hsl(var(--color-card-border))',
          },
          nav: 'hsl(var(--theme-surface) / 0.9)',
        },

        btn: {
          'default-bg': 'hsl(var(--color-button-default-bg))',
          'default-fg': 'hsl(var(--color-button-default-text))',
          'default-bg-hover': 'hsl(var(--color-button-default-bg-hover))',
          'default-fg-hover': 'hsl(var(--color-button-default-text-hover))',
          'destructive-bg': 'hsl(var(--color-button-destructive-bg))',
          'destructive-fg': 'hsl(var(--color-button-destructive-text))',
          'destructive-bg-hover': 'hsl(var(--color-button-destructive-bg-hover))',
          'outline-bg': 'hsl(var(--color-button-outline-bg))',
          'outline-fg': 'hsl(var(--color-button-outline-text))',
          'outline-border': 'hsl(var(--color-button-outline-border))',
          'outline-bg-hover': 'hsl(var(--color-button-outline-bg-hover))',
          'outline-fg-hover': 'hsl(var(--color-button-outline-text-hover))',
          'secondary-bg': 'hsl(var(--color-button-secondary-bg))',
          'secondary-fg': 'hsl(var(--color-button-secondary-text))',
          'secondary-bg-hover': 'hsl(var(--color-button-secondary-bg-hover))',
          'ghost-bg-hover': 'hsl(var(--color-button-ghost-bg-hover))',
          'ghost-fg-hover': 'hsl(var(--color-button-ghost-text-hover))',
          'link-fg': 'hsl(var(--color-button-link-text))',
        },
        inputx: {
          bg: 'hsl(var(--color-input-bg))',
          text: 'hsl(var(--color-input-text))',
          border: 'hsl(var(--color-input-border))',
          placeholder: 'hsl(var(--color-input-placeholder))',
          'border-focus': 'hsl(var(--color-input-border-focus))',
          ring: 'hsl(var(--color-input-ring))',
        },
        selectx: {
          'trigger-bg': 'hsl(var(--color-select-trigger-bg))',
          'trigger-text': 'hsl(var(--color-select-trigger-text))',
          'trigger-border': 'hsl(var(--color-select-trigger-border))',
          'trigger-ring': 'hsl(var(--color-select-trigger-ring))',
          'content-bg': 'hsl(var(--color-select-content-bg))',
          'content-text': 'hsl(var(--color-select-content-text))',
          'content-border': 'hsl(var(--color-select-content-border))',
          'item-text': 'hsl(var(--color-select-item-text))',
          'item-bg-hover': 'hsl(var(--color-select-item-bg-hover))',
          separator: 'hsl(var(--color-select-separator))',
        },
        badge: {
          'default-bg': 'hsl(var(--color-badge-default-bg))',
          'default-text': 'hsl(var(--color-badge-default-text))',
          'default-border': 'hsl(var(--color-badge-default-border))',
          'secondary-bg': 'hsl(var(--color-badge-secondary-bg))',
          'secondary-text': 'hsl(var(--color-badge-secondary-text))',
          'outline-bg': 'hsl(var(--color-badge-outline-bg))',
          'outline-text': 'hsl(var(--color-badge-outline-text))',
          'outline-border': 'hsl(var(--color-badge-outline-border))',
          'destructive-bg': 'hsl(var(--color-badge-destructive-bg))',
          'destructive-text': 'hsl(var(--color-badge-destructive-text))',
        },
        swt: {
          'bg-checked': 'hsl(var(--color-switch-bg-checked))',
          'bg-checked-hover': 'hsl(var(--color-switch-bg-checked-hover))',
          'bg-unchecked': 'hsl(var(--color-switch-bg-unchecked))',
          'border-unchecked': 'hsl(var(--color-switch-border-unchecked))',
          'thumb-bg': 'hsl(var(--color-switch-thumb-bg))',
          ring: 'hsl(var(--color-switch-ring))',
        },
        dlg: {
          'overlay-bg': 'hsl(var(--color-dialog-overlay-bg))',
          'content-bg': 'hsl(var(--color-dialog-content-bg))',
          'content-border': 'hsl(var(--color-dialog-content-border))',
          'close-bg-hover': 'hsl(var(--color-dialog-close-bg-hover))',
          'close-fg-hover': 'hsl(var(--color-dialog-close-text-hover))',
          'title-fg': 'hsl(var(--color-dialog-title-text))',
          'desc-fg': 'hsl(var(--color-dialog-desc-text))',
          'ring-color': 'hsl(var(--color-dialog-ring))',
        },
        avt: {
          'fallback-bg': 'hsl(var(--color-avatar-fallback-bg))',
          'fallback-fg': 'hsl(var(--color-avatar-fallback-text))',
        },
        ddm: {
          'content-bg': 'hsl(var(--color-dropdown-content-bg))',
          'content-border': 'hsl(var(--color-dropdown-content-border))',
          'content-fg': 'hsl(var(--color-dropdown-content-text))',
          'item-bg-hover': 'hsl(var(--color-dropdown-item-bg-hover))',
          'item-fg-hover': 'hsl(var(--color-dropdown-item-text-hover))',
          'separator-bg': 'hsl(var(--color-dropdown-separator))',
          'label-fg': 'hsl(var(--color-dropdown-label-text))',
        },
        tbl: {
          'footer-bg': 'hsl(var(--color-table-footer-bg))',
          'row-bg-hover': 'hsl(var(--color-table-row-bg-hover))',
          'row-bg-selected': 'hsl(var(--color-table-row-bg-selected))',
          'head-fg': 'hsl(var(--color-table-head-text))',
          'caption-fg': 'hsl(var(--color-table-caption-text))',
        },
        sht: {
          'overlay-bg': 'hsl(var(--color-sheet-overlay-bg))',
          'content-bg': 'hsl(var(--color-sheet-content-bg))',
          'content-border': 'hsl(var(--color-sheet-content-border))',
          'close-bg-hover': 'hsl(var(--color-sheet-close-bg-hover))',
          'close-fg-hover': 'hsl(var(--color-sheet-close-text-hover))',
          'title-fg': 'hsl(var(--color-sheet-title-text))',
          'desc-fg': 'hsl(var(--color-sheet-desc-text))',
          'ring-color': 'hsl(var(--color-sheet-ring))',
        },
      },
      fontFamily: {
        sans: ['var(--font-outfit)', 'system-ui', 'sans-serif'],
        mono: ['var(--font-jetbrains-mono)', 'monospace'],
      },
      letterSpacing: {
        tighter: '-0.04em',
      },
      boxShadow: {
        card: 'var(--color-card-shadow)',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}

export default config
